# Generated by Django 5.1.13 on 2025-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudio_videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
