# Generated by Django 5.1.13 on 2025-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudio_videojuegos', '0002_alter_videojuego_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
